apiVersion: v1
kind: Service
metadata:
  name: gatling-service
  namespace: hobigon
  labels:
    app: gatling
spec:
  type: ClusterIP
  selector:
    app: gatling
  ports:
    - port: 9090
      targetPort: 9090
