apiVersion: 1
groups:
    - orgId: 1
      name: hobigon-api
      folder: hobigon
      interval: 1m
      rules:
        - uid: b844e109-aabe-41b6-a46a-2848a49496be
          title: rps by code
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: sum by(code)(rate(http_requests_total[1m]))
                format: time_series
                interval: ""
                intervalMs: 30000
                legendFormat: '{{code}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 35
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "35"
          isPaused: false
        - uid: a7ecc1fd-9d73-4d7b-bca0-72ceeb7d1c16
          title: 4xx Error Rate
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: |-
                    sum by(method)(rate(http_requests_total{code=~"4.."}[1m]))
                    /
                    sum by(method)(rate(http_requests_total[1m]))
                format: time_series
                interval: ""
                intervalMs: 30000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 36
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "36"
          isPaused: false
        - uid: cc60fef4-d3b5-4123-bd20-67b8ad70d669
          title: 5xx Error Rate
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: |-
                    sum by(method)(rate(http_requests_total{code=~"5.."}[1m]))
                    /
                    sum by(method)(rate(http_requests_total[1m]))
                format: time_series
                interval: ""
                intervalMs: 30000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 37
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "37"
          isPaused: false
        - uid: f72a7c70-5648-4508-a2df-7176753dfd6f
          title: Duration 50%ile (POST)
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: max by(method) (histogram_quantile(0.5, rate(request_duration_seconds_bucket{method="post"}[1m])))
                format: time_series
                interval: ""
                intervalMs: 30000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.25
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 39
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "39"
          isPaused: false
        - uid: a44f10ae-754a-4e46-af0f-fddc287c477b
          title: Duration 50%ile
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: max by(method) (histogram_quantile(0.5, rate(request_duration_seconds_bucket{method="get"}[1m])))
                format: time_series
                interval: ""
                intervalMs: 30000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.25
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 39
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "39"
          isPaused: false
