apiVersion: 1
groups:
    - orgId: 1
      name: hobigon
      folder: Services
      interval: 1m
      rules:
        - uid: f9205cfe-ef09-4a21-b033-85b67d68eb4c
          title: 4xx Error Rate
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
              model:
                datasource:
                    type: prometheus
                    uid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
                editorMode: code
                expr: sum by(method) (rate(http_requests_total{code=~"4..", pod=~".+", method=~".+", path=~".+"}[5m])) / sum by(method) (rate(http_requests_total{pod=~".+", method=~".+", path=~".+"}[5m]))
                format: time_series
                interval: ""
                intervalMs: 15000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                queryType: range
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 36
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "36"
          labels:
            service: hobigon
          isPaused: false
        - uid: f70a76a2-172c-40ed-9a2f-c9624fd61c8e
          title: 5xx Error Rate
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
              model:
                datasource:
                    type: prometheus
                    uid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
                editorMode: code
                expr: sum by(method) (rate(http_requests_total{code=~"5..", pod=~".+", method=~".+", path=~".+"}[5m])) / sum by(method) (rate(http_requests_total{pod=~".+", method=~".+", path=~".+"}[5m]))
                format: time_series
                interval: ""
                intervalMs: 15000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                queryType: range
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 37
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "37"
          labels:
            service: hobigon
          isPaused: false
        - uid: da8f5634-e595-4b62-9ae5-0291629a30cc
          title: Duration 50%ile
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
              model:
                datasource:
                    type: prometheus
                    uid: ad50a36c-3fc3-4774-83a2-b7c45eae07a0
                editorMode: code
                expr: max by(method) (histogram_quantile(0.5, rate(request_duration_seconds_bucket{pod=~".+", method=~".+"}[5m])))
                format: time_series
                interval: ""
                intervalMs: 15000
                legendFormat: '{{method}}'
                maxDataPoints: 43200
                queryType: range
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.25
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: CgCw8jKZz
          panelId: 39
          noDataState: NoData
          execErrState: Error
          for: 10m
          annotations:
            __dashboardUid__: CgCw8jKZz
            __panelId__: "39"
          labels:
            service: hobigon
          isPaused: false
