apiVersion: batch/v1
kind: CronJob
metadata:
  name: mother-seisenkan-payment-notification
  namespace: batch
spec:
  # 毎月5日, 15日, 25日 9, 12時（JST）
  schedule: 0 0,3 5,15,25 * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mother-seisenkan-payment-notification
              image: alpine/curl
              env:
                - name: LINE_CHANNEL_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: batch-secret
                      key: line-channel-access-token-of-son-bot
                      optional: false
              command:
                - /bin/sh
                - -c
                - |
                  curl -v -X POST https://api.line.me/v2/bot/message/broadcast \
                    -H 'Content-Type: application/json' \
                    -H "Authorization: Bearer $LINE_CHANNEL_ACCESS_TOKEN" \
                    -d '{
                      "messages":[
                        {
                          "type": "text",
                          "text": "今日は生鮮館に入金する日"
                        }
                      ]
                    }'
          restartPolicy: OnFailure
