apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-grafana-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /var/k8s/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-14100000506122 # Master node
                - i-14100000506123 # Worker node
  persistentVolumeReclaimPolicy: Retain
