prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: "128Mi"
    scrapeInterval: "1m"
    # FIXME: This is not working
    #    serviceMonitorNamespaceSelector:
    #      matchNames:
    #        - hobigon
    additionalScrapeConfigs:
      - job_name: 'hobigon-monitor'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_container_port_number
            regex: hobigon;(3000|9090)
            action: keep
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
    remoteWrite:
      - url: https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: grafana-cloud-secret
            key: username
            optional: false
          password:
            name: grafana-cloud-secret
            key: password
            optional: false
# FIXME: This is not working
#  additionalRulesForClusterRole:
#    - apiGroups: [""]
#      resources: ["nodes", "services", "endpoints", "pods"]
#      verbs: ["get", "list", "watch"]
#  additionalServiceMonitors:
#    - name: hobigon-api-monitor
#      namespaceSelector:
#        matchNames:
#          - hobigon
#      selector:
#        matchLabels:
#          app: hobigon-api
#      endpoints:
#        - port: "3000"
#          interval: "5s"

grafana:
  defaultDashboardsTimezone: Asia/Tokyo
  grafana.ini:
    server:
      root_url: https://monitoring.yyh-gl.dev
