prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: "128Mi"
    scrapeInterval: "1m"

grafana:
  defaultDashboardsTimezone: Asia/Tokyo
  grafana.ini:
    server:
      root_url: https://monitoring.yyh-gl.dev
  persistence:
    enabled: true
    type: sts
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection
