{
 "title": "Metrics",
 "tags": [
  "go",
  "backend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "method", "query": { "query": "label_values(method)" } },
   { "name": "path", "query": { "query": "label_values(path)" } }
  ]
 },
 "panels": [
  {
   "title": "Running version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(version) (running_version{pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests/sec by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total{pod=~\"$pod\", method=~\"$method\", path=~\"$path\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests/sec by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_requests_total{pod=~\"$pod\", method=~\"$method\", path=~\"$path\"} [5m]))"
    }
   ]
  },
  {
   "title": "4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total{code=~\"4..\", pod=~\"$pod\", method=~\"$method\", path=~\"$path\"}[5m])) / sum by(method) (rate(http_requests_total{pod=~\"$pod\", method=~\"$method\", path=~\"$path\"}[5m]))"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total{code=~\"5..\", pod=~\"$pod\", method=~\"$method\", path=~\"$path\"}[5m])) / sum by(method) (rate(http_requests_total{pod=~\"$pod\", method=~\"$method\", path=~\"$path\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(method) (rate(request_duration_seconds_sum{pod=~\"$pod\", method=~\"$method\"}[5m]) / rate(request_duration_seconds_count{pod=~\"$pod\", method=~\"$method\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration 50%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(method) (histogram_quantile(0.5, rate(request_duration_seconds_bucket{pod=~\"$pod\", method=~\"$method\"}[5m])))"
    }
   ]
  },
  {
   "title": "Duration 90%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(method) (histogram_quantile(0.9, rate(request_duration_seconds_bucket{pod=~\"$pod\", method=~\"$method\"}[5m])))"
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"} - go_memstats_other_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"} - go_memstats_frees_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}