apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobigon-user-box-deployment
  labels:
    app: hobigon-user-box
  namespace: hobigon
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hobigon-user-box
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hobigon-user-box
      namespace: hobigon
    spec:
      containers:
        - name: hobigon-user-box
          image: ghcr.io/yyh-gl/hobigon-user-box
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 100Mi
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/health
            periodSeconds: 5
