apiVersion: v1
kind: Service
metadata:
  name: hobigon-user-box-service
  namespace: hobigon
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hobigon-user-box
